/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica_agendamiento;

/**
 *
 * @author Andreina
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Agendamiento = new javax.swing.JMenu();
        itmAgendamiento = new javax.swing.JMenuItem();
        itmPciente = new javax.swing.JMenuItem();
        itmDoctor = new javax.swing.JMenuItem();
        itmTurno = new javax.swing.JMenuItem();
        itmEspecialidades = new javax.swing.JMenuItem();
        itmEnfermedad = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        itmCiudad = new javax.swing.JMenu();
        itmCiudades = new javax.swing.JMenuItem();
        itmBarrio = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(0, 0, 51));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Georgia", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("CLÍNICA");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 70)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("SISTEMA DE GESTIÓN");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/caduceus.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/medical-team.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Felix Titling", 0, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("VERSIÓN 2025");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));

        Agendamiento.setText("MÓDULOS");

        itmAgendamiento.setText("Agendamiento");
        itmAgendamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAgendamientoActionPerformed(evt);
            }
        });
        Agendamiento.add(itmAgendamiento);

        itmPciente.setText("Paciente");
        itmPciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPcienteActionPerformed(evt);
            }
        });
        Agendamiento.add(itmPciente);

        itmDoctor.setText("Doctor");
        itmDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDoctorActionPerformed(evt);
            }
        });
        Agendamiento.add(itmDoctor);

        itmTurno.setText("Turno del Doctor");
        itmTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTurnoActionPerformed(evt);
            }
        });
        Agendamiento.add(itmTurno);

        itmEspecialidades.setText("Especialidades del Doctor");
        itmEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEspecialidadesActionPerformed(evt);
            }
        });
        Agendamiento.add(itmEspecialidades);

        itmEnfermedad.setText("Enfermedad");
        itmEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEnfermedadActionPerformed(evt);
            }
        });
        Agendamiento.add(itmEnfermedad);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Agendamiento.add(jMenuItem5);

        jMenuBar1.add(Agendamiento);

        itmCiudad.setText("PRIVADOS");

        itmCiudades.setText("Ciudad");
        itmCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCiudadesActionPerformed(evt);
            }
        });
        itmCiudad.add(itmCiudades);

        itmBarrio.setText("Barrio");
        itmBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBarrioActionPerformed(evt);
            }
        });
        itmCiudad.add(itmBarrio);

        jMenuBar1.add(itmCiudad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmPcienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPcienteActionPerformed
        FrmPacientes pacientes =new FrmPacientes(this,false);
        pacientes.setVisible(true);
    }//GEN-LAST:event_itmPcienteActionPerformed

    private void itmDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDoctorActionPerformed
        FrmDoctores doctores =new FrmDoctores(this,false);
        doctores.setVisible(true);
    }//GEN-LAST:event_itmDoctorActionPerformed

    private void itmTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTurnoActionPerformed
        FrmTurnos turnos =new FrmTurnos(this,false);
        turnos.setVisible(true);
    }//GEN-LAST:event_itmTurnoActionPerformed

    private void itmEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEspecialidadesActionPerformed
        FrmEspecialidades especialidades =new FrmEspecialidades(this,false);
        especialidades.setVisible(true);
    }//GEN-LAST:event_itmEspecialidadesActionPerformed

    private void itmEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEnfermedadActionPerformed
        FrmEnfermedades enfermedades =new FrmEnfermedades(this,false);
        enfermedades.setVisible(true);
    }//GEN-LAST:event_itmEnfermedadActionPerformed

    private void itmCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCiudadesActionPerformed
        FrmCiudades ciudades =new FrmCiudades(this,false);
        ciudades.setVisible(true);
    }//GEN-LAST:event_itmCiudadesActionPerformed

    private void itmBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBarrioActionPerformed
        FrmBarrio barrios =new FrmBarrio(this,false);
        barrios.setVisible(true);
    }//GEN-LAST:event_itmBarrioActionPerformed

    private void itmAgendamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAgendamientoActionPerformed
        FrmAgendamientos Agendamientos =new FrmAgendamientos(this,false);
        Agendamientos.setVisible(true);
    }//GEN-LAST:event_itmAgendamientoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Agendamiento;
    private javax.swing.JMenuItem itmAgendamiento;
    private javax.swing.JMenuItem itmBarrio;
    private javax.swing.JMenu itmCiudad;
    private javax.swing.JMenuItem itmCiudades;
    private javax.swing.JMenuItem itmDoctor;
    private javax.swing.JMenuItem itmEnfermedad;
    private javax.swing.JMenuItem itmEspecialidades;
    private javax.swing.JMenuItem itmPciente;
    private javax.swing.JMenuItem itmTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
